#!/usr/bin/expect -f
set arg1 [lindex $argv 0]
spawn ssh $arg1
expect {
 "Are you sure you want to continue connecting (yes/no)?" {
  send "yes\n"
  exp_continue
  }
 "mcanal@$arg1's password: " {
  send "mdp"
 }
}
interact
